#!/bin/bash

set -e

sudo yum -y update
sudo yum -y install epel-release yum-utils wget git

sudo yum-config-manager --set-enabled powertools
sudo yum-config-manager --set-enabled appstream

sudo wget -O /etc/yum.repos.d/EGI-trustanchors.repo http://repository.egi.eu/sw/production/cas/1/current/repo-files/EGI-trustanchors.repo
sudo yum -y install ca-policy-egi-core
sudo ln -s /etc/grid-security/certificates/USERTrustRSACertificationAuthority.pem /etc/pki/ca-trust/source/anchors/
sudo ln -s /etc/grid-security/certificates/GEANTeScienceSSLCA4.pem /etc/pki/ca-trust/source/anchors/
sudo update-ca-trust extract

sudo wget -O /etc/yum.repos.d/mc-extras.repo https://cld-smact-02.pd.infn.it/artifacts/repository/repo-files/mc-extras.repo
sudo wget -O /etc/yum.repos.d/geant4.repo https://cld-smact-02.pd.infn.it/artifacts/repository/repo-files/geant4.repo
sudo wget -O /etc/yum.repos.d/root.repo https://cld-smact-02.pd.infn.it/artifacts/repository/repo-files/root-c17.repo

sudo yum -y install boost169-devel chrpath clhep-devel cmake doxygen \
                    eigen3-devel freeglut-devel geant4-devel HepMC3-devel \
                    gsl-devel make mysql-devel python36 python36-devel \
                    python36-rpm-macros python3-root root root-gdml \
                    root-genvector root-geom root-graf3d-eve root-tpython \
                    root-tmva root-minuit2 root-unuran root-smatrix \
                    root-graf3d-eve7 root-gui-browserv7 zlib-devel rpm-build

#sudo geant4-dataset-download

sudo sed -i 's|include_next|include|g' /usr/include/c++/8/cstdlib
sudo sed -i 's|include_next|include|g' /usr/include/c++/8/bits/std_abs.h
sudo sed -i 's|include_next|include|g' /usr/include/c++/8/cmath

cat << EOF > $HOME/.rpmmacros
%mc_source_url https://cld-smact-02.pd.infn.it/artifacts/repository/mc-sources
EOF

sudo alternatives --set python /usr/bin/python3

git clone https://github.com/MuonColliderSoft/MuonCollider-rpms.git
ln -s $HOME/MuonCollider-rpms/CentOS8/ $HOME/rpmbuild
cd rpmbuild
mkdir DEBUGINFO DEBUGSOURCES

rpmbuild -ba SPECS/ilc-utils.spec
mv RPMS/x86_64/*-debuginfo-*.rpm DEBUGINFO
mv RPMS/x86_64/*-debugsource-*.rpm DEBUGSOURCES
sudo yum -y localinstall RPMS/x86_64/ilc-utils*

rpmbuild -ba SPECS/ilc-ced.spec
rpmbuild -ba SPECS/ilc-gear.spec
rpmbuild -ba SPECS/ilc-fastjet.spec
rpmbuild -ba SPECS/ilc-cond-db-mysql.spec
rpmbuild -ba SPECS/ilc-lcio.spec
rpmbuild -ba SPECS/gbl.spec
rpmbuild -ba SPECS/root-aida.spec
rpmbuild -ba SPECS/ilc-kaltest.spec
QA_SKIP_BUILD_ROOT=1 rpmbuild -ba SPECS/pandora-pfa.spec
#rpmbuild -ba SPECS/ilc-physsim.spec
mv RPMS/x86_64/*-debuginfo-*.rpm DEBUGINFO
mv RPMS/x86_64/*-debugsource-*.rpm DEBUGSOURCES
sudo yum -y localinstall RPMS/x86_64/ilc-ced* \
                         RPMS/x86_64/ilc-gear* \
                         RPMS/x86_64/ilc-fastjet* \
                         RPMS/x86_64/ilc-cond-db-mysql* \
                         RPMS/x86_64/ilc-lcio* \
                         RPMS/x86_64/gbl* \
                         RPMS/x86_64/root-aida* \
                         RPMS/x86_64/ilc-kaltest* \
                         RPMS/x86_64/pandora-pfa*

rpmbuild -ba SPECS/aida-dd4hep.spec
rpmbuild -ba SPECS/ilc-lccd.spec
rpmbuild -ba SPECS/ilc-fastjet-contrib.spec
mv RPMS/x86_64/*-debuginfo-*.rpm DEBUGINFO
mv RPMS/x86_64/*-debugsource-*.rpm DEBUGSOURCES
sudo yum -y localinstall RPMS/x86_64/aida-dd4hep* \
                         RPMS/x86_64/ilc-lccd* \
                         RPMS/x86_64/ilc-fastjet-contrib*

rpmbuild -ba SPECS/aida-tracking-toolkit.spec
rpmbuild -ba SPECS/ilc-marlin.spec
rpmbuild -ba SPECS/ilc-lcgeo.spec
mv RPMS/x86_64/*-debuginfo-*.rpm DEBUGINFO
mv RPMS/x86_64/*-debugsource-*.rpm DEBUGSOURCES
sudo yum -y localinstall RPMS/x86_64/aida-tracking-toolkit* \
                         RPMS/x86_64/ilc-marlin*

rpmbuild -ba SPECS/ilc-marlin-util.spec
rpmbuild -ba SPECS/ilc-ddkaltest.spec
rpmbuild -ba SPECS/ilc-fcal-clusterer.spec
rpmbuild -ba SPECS/ilc-kitrack.spec
rpmbuild -ba SPECS/ilc-lctuple.spec
rpmbuild -ba SPECS/ilc-marlin-dd4hep.spec
rpmbuild -ba SPECS/ilc-marlin-fastjet.spec
rpmbuild -ba SPECS/ilc-marlin-kinfit.spec
mv RPMS/x86_64/*-debuginfo-*.rpm DEBUGINFO
mv RPMS/x86_64/*-debugsource-*.rpm DEBUGSOURCES
sudo yum -y localinstall RPMS/x86_64/ilc-marlin-util* \
                         RPMS/x86_64/ilc-ddkaltest* \
                         RPMS/x86_64/ilc-kitrack* \
                         RPMS/x86_64/ilc-marlin-kinfit*

rpmbuild -ba SPECS/ilc-ced-viewer.spec
rpmbuild -ba SPECS/ilc-kaldet.spec
rpmbuild -ba SPECS/ilc-garlic.spec
rpmbuild -ba SPECS/ilc-lcfi-vertex.spec
rpmbuild -ba SPECS/ilc-marlin-kinfit-processors.spec
rpmbuild -ba SPECS/ilc-marlin-lich.spec
rpmbuild -ba SPECS/ilc-overlay.spec
rpmbuild -ba SPECS/pandora-analysis.spec
mv RPMS/x86_64/*-debuginfo-*.rpm DEBUGINFO
mv RPMS/x86_64/*-debugsource-*.rpm DEBUGSOURCES
sudo yum -y localinstall RPMS/x86_64/ilc-ced-viewer* \
                         RPMS/x86_64/ilc-kaldet* \
                         RPMS/x86_64/ilc-lcfi-vertex*

rpmbuild -ba SPECS/ilc-marlin-trk.spec
rpmbuild -ba SPECS/ilc-lcfi-plus.spec
mv RPMS/x86_64/*-debuginfo-*.rpm DEBUGINFO
mv RPMS/x86_64/*-debugsource-*.rpm DEBUGSOURCES
sudo yum -y localinstall RPMS/x86_64/ilc-marlin-trk*

rpmbuild -ba SPECS/ilc-clupatra.spec
rpmbuild -ba SPECS/ilc-conformal-tracking.spec
rpmbuild -ba SPECS/ilc-ddmarlin-pandora.spec
rpmbuild -ba SPECS/ilc-kitrack-marlin.spec
rpmbuild -ba SPECS/ilc-ild-performance.spec
rpmbuild -ba SPECS/ilc-marlin-reco.spec
mv RPMS/x86_64/*-debuginfo-*.rpm DEBUGINFO
mv RPMS/x86_64/*-debugsource-*.rpm DEBUGSOURCES
sudo yum -y localinstall RPMS/x86_64/ilc-ddmarlin-pandora* \
                         RPMS/x86_64/ilc-kitrack-marlin*

rpmbuild -ba SPECS/ilc-forward-tracking.spec
rpmbuild -ba SPECS/ilc-marlin-trk-processors.spec
rpmbuild -ba SPECS/muonc-detector-geometry.spec
mv RPMS/x86_64/*-debuginfo-*.rpm DEBUGINFO
mv RPMS/x86_64/*-debugsource-*.rpm DEBUGSOURCES

# Install all packages
sudo yum -y localinstall RPMS/x86_64/ilc-lcgeo* \
                         RPMS/x86_64/ilc-fcal-clusterer* \
                         RPMS/x86_64/ilc-lctuple* \
                         RPMS/x86_64/ilc-marlin-dd4hep* \
                         RPMS/x86_64/ilc-marlin-fastjet* \
                         RPMS/x86_64/ilc-garlic* \
                         RPMS/x86_64/ilc-marlin-kinfit-processors* \
                         RPMS/x86_64/ilc-marlin-lich* \
                         RPMS/x86_64/ilc-overlay* \
                         RPMS/x86_64/pandora-analysis* \
                         RPMS/x86_64/ilc-lcfi-plus* \
                         RPMS/x86_64/ilc-clupatra* \
                         RPMS/x86_64/ilc-conformal-tracking* \
                         RPMS/x86_64/ilc-ild-performance* \
                         RPMS/x86_64/ilc-marlin-reco* \
                         RPMS/x86_64/ilc-forward-tracking* \
                         RPMS/x86_64/ilc-marlin-trk-processors* \
                         RPMS/noarch/python3-lcio* \
                         RPMS/noarch/python3-dd4hep* \
                         RPMS/noarch/muonc-detector-geometry*


## https://root.cern/manual/python/

## Problems:
# file /usr/lib64/utilsDict_rdict.pcm from install of ilc-physsim-0.4.1-1.el8.x86_64 conflicts with file from package ilc-kaltest-2.5.0-1.el8.x86_64



