#!/bin/bash

set -e

git clone https://github.com/MuonColliderSoft/MuonCollider-rpms.git
ln -s $HOME/MuonCollider-rpms/CentOS8/ $HOME/rpmbuild
cd rpmbuild

rpmbuild -ba SPECS/ilc-utils.spec
sudo yum -y localinstall RPMS/x86_64/ilc-utils*

rpmbuild -ba SPECS/ilc-ced.spec
rpmbuild -ba SPECS/ilc-gear.spec
rpmbuild -ba SPECS/ilc-fastjet.spec
rpmbuild -ba SPECS/ilc-cond-db-mysql.spec
rpmbuild -ba SPECS/ilc-lcio.spec
rpmbuild -ba SPECS/gbl.spec
rpmbuild -ba SPECS/root-aida.spec
rpmbuild -ba SPECS/ilc-kaltest.spec
QA_SKIP_BUILD_ROOT=1 rpmbuild -ba SPECS/pandora-pfa.spec
rpmbuild -ba SPECS/acts-toolkit.spec
#rpmbuild -ba SPECS/ilc-physsim.spec
sudo yum -y localinstall RPMS/x86_64/ilc-ced* \
                         RPMS/x86_64/ilc-gear* \
                         RPMS/x86_64/ilc-fastjet* \
                         RPMS/x86_64/ilc-cond-db-mysql* \
                         RPMS/x86_64/ilc-lcio* \
                         RPMS/x86_64/gbl* \
                         RPMS/x86_64/root-aida* \
                         RPMS/x86_64/ilc-kaltest* \
                         RPMS/x86_64/pandora-pfa* \
                         RPMS/x86_64/acts-toolkit*

rpmbuild -ba SPECS/aida-dd4hep.spec
rpmbuild -ba SPECS/ilc-lccd.spec
rpmbuild -ba SPECS/ilc-fastjet-contrib.spec
sudo yum -y localinstall RPMS/x86_64/aida-dd4hep* \
                         RPMS/x86_64/ilc-lccd* \
                         RPMS/x86_64/ilc-fastjet-contrib*

rpmbuild -ba SPECS/aida-tracking-toolkit.spec
rpmbuild -ba SPECS/ilc-marlin.spec
rpmbuild -ba SPECS/ilc-lcgeo.spec
sudo yum -y localinstall RPMS/x86_64/aida-tracking-toolkit* \
                         RPMS/x86_64/ilc-marlin*

rpmbuild -ba SPECS/ilc-marlin-util.spec
rpmbuild -ba SPECS/ilc-ddkaltest.spec
rpmbuild -ba SPECS/ilc-fcal-clusterer.spec
rpmbuild -ba SPECS/ilc-kitrack.spec
rpmbuild -ba SPECS/ilc-lctuple.spec
rpmbuild -ba SPECS/ilc-marlin-dd4hep.spec
rpmbuild -ba SPECS/ilc-marlin-fastjet.spec
rpmbuild -ba SPECS/ilc-marlin-kinfit.spec
sudo yum -y localinstall RPMS/x86_64/ilc-marlin-util* \
                         RPMS/x86_64/ilc-ddkaltest* \
                         RPMS/x86_64/ilc-kitrack* \
                         RPMS/x86_64/ilc-marlin-kinfit*

rpmbuild -ba SPECS/ilc-ced-viewer.spec
rpmbuild -ba SPECS/ilc-kaldet.spec
rpmbuild -ba SPECS/ilc-garlic.spec
rpmbuild -ba SPECS/ilc-lcfi-vertex.spec
rpmbuild -ba SPECS/ilc-marlin-kinfit-processors.spec
rpmbuild -ba SPECS/ilc-marlin-lich.spec
rpmbuild -ba SPECS/ilc-overlay.spec
rpmbuild -ba SPECS/pandora-analysis.spec
rpmbuild -ba SPECS/ilc-lcfi-plus-headers.spec
sudo yum -y localinstall RPMS/x86_64/ilc-ced-viewer* \
                         RPMS/x86_64/ilc-kaldet* \
                         RPMS/x86_64/ilc-lcfi-vertex* \
                         RPMS/x86_64/ilc-lcfi-plus-headers*

rpmbuild -ba SPECS/ilc-marlin-trk.spec
rpmbuild -ba SPECS/ilc-lcfi-plus.spec
sudo yum -y localinstall RPMS/x86_64/ilc-marlin-trk*

rpmbuild -ba SPECS/ilc-clupatra.spec
rpmbuild -ba SPECS/ilc-conformal-tracking.spec
rpmbuild -ba SPECS/ilc-ddmarlin-pandora.spec
rpmbuild -ba SPECS/ilc-kitrack-marlin.spec
rpmbuild -ba SPECS/ilc-ild-performance.spec
rpmbuild -ba SPECS/ilc-clic-performance.spec
rpmbuild -ba SPECS/ilc-marlin-reco.spec
rpmbuild -ba SPECS/ilc-acts-tracking.spec
sudo yum -y localinstall RPMS/x86_64/ilc-ddmarlin-pandora* \
                         RPMS/x86_64/ilc-kitrack-marlin*

rpmbuild -ba SPECS/ilc-forward-tracking.spec
rpmbuild -ba SPECS/ilc-marlin-trk-processors.spec
rpmbuild -ba SPECS/muonc-detector-geometry.spec

# Install all packages
sudo yum -y localinstall RPMS/x86_64/ilc-lcgeo* \
                         RPMS/x86_64/ilc-fcal-clusterer* \
                         RPMS/x86_64/ilc-lctuple* \
                         RPMS/x86_64/ilc-marlin-dd4hep* \
                         RPMS/x86_64/ilc-marlin-fastjet* \
                         RPMS/x86_64/ilc-garlic* \
                         RPMS/x86_64/ilc-marlin-kinfit-processors* \
                         RPMS/x86_64/ilc-marlin-lich* \
                         RPMS/x86_64/ilc-overlay* \
                         RPMS/x86_64/pandora-analysis* \
                         RPMS/x86_64/ilc-lcfi-plus* \
                         RPMS/x86_64/ilc-clupatra* \
                         RPMS/x86_64/ilc-conformal-tracking* \
                         RPMS/x86_64/ilc-ild-performance* \
                         RPMS/x86_64/ilc-clic-performance* \
                         RPMS/x86_64/ilc-marlin-reco* \
                         RPMS/x86_64/ilc-forward-tracking* \
                         RPMS/x86_64/ilc-marlin-trk-processors* \
                         RPMS/x86_64/ilc-acts-tracking* \
                         RPMS/noarch/python3-lcio* \
                         RPMS/noarch/python3-dd4hep* \
                         RPMS/noarch/muonc-detector-geometry*


## https://root.cern/manual/python/

## Problems:
# file /usr/lib64/utilsDict_rdict.pcm from install of ilc-physsim-0.4.1-1.el8.x86_64 conflicts with file from package ilc-kaltest-2.5.0-1.el8.x86_64


## Packages for minimal test:
#simulation: python3-dd4hep muonc-detector-geometry
#reco: ilc-marlin-dd4hep ilc-marlin-fastjet ilc-marlin-kinfit-processors 
#      ilc-overlay ilc-lcfi-plus ilc-conformal-tracking ilc-marlin-reco 
#      ilc-forward-tracking ilc-marlin-trk-processors ilc-ced-viewer 
#      ilc-ddmarlin-pandora ilc-lctuple ilc-clic-performance



