#!/bin/bash


#
# Apply patches as reported in the recipe:
#
# #undef _GLIBCXX_ASSERTIONS in
# /usr/include/c++/11/x86_64-redhat-linux/bits/c++config.h
# /usr/include/c++/11/x86_64-redhat-linux/32/bits/c++config.h 
#

set -e

rpmbuild -ba SPECS/ilc-utils.spec
sudo yum -y localinstall RPMS/x86_64/ilc-utils*

rpmbuild -ba SPECS/ilc-ced.spec
rpmbuild -ba SPECS/ilc-gear.spec
rpmbuild -ba SPECS/fastjet.spec
rpmbuild -ba SPECS/ilc-lcio.spec
rpmbuild -ba SPECS/gbl-toolkit.spec
rpmbuild -ba SPECS/ilc-root-aida.spec
rpmbuild -ba SPECS/ilc-kaltest.spec
QA_SKIP_BUILD_ROOT=1 rpmbuild -ba SPECS/pandora-pfa.spec
sudo yum -y localinstall RPMS/x86_64/ilc-ced* \
                         RPMS/x86_64/ilc-gear* \
                         RPMS/x86_64/fastjet* \
                         RPMS/x86_64/ilc-lcio* \
                         RPMS/x86_64/gbl-toolkit* \
                         RPMS/x86_64/ilc-root-aida* \
                         RPMS/x86_64/ilc-kaltest* \
                         RPMS/x86_64/pandora-pfa*

rpmbuild -ba SPECS/aida-dd4hep.spec
rpmbuild -ba SPECS/fastjet-contrib.spec
sudo yum -y localinstall RPMS/x86_64/aida-dd4hep* \
                         RPMS/x86_64/fastjet-contrib*

rpmbuild -ba SPECS/acts-toolkit.spec
rpmbuild -ba SPECS/aida-tracking-toolkit.spec
rpmbuild -ba SPECS/ilc-marlin.spec
rpmbuild -ba SPECS/ilc-lcgeo.spec
sudo yum -y localinstall RPMS/x86_64/aida-tracking-toolkit* \
                         RPMS/x86_64/acts-toolkit* \
                         RPMS/x86_64/ilc-marlin*

rpmbuild -ba SPECS/ilc-marlin-util.spec
rpmbuild -ba SPECS/ilc-ddkaltest.spec
rpmbuild -ba SPECS/ilc-kitrack.spec
rpmbuild -ba SPECS/ilc-lctuple.spec
rpmbuild -ba SPECS/ilc-marlin-dd4hep.spec
rpmbuild -ba SPECS/ilc-marlin-fastjet.spec
rpmbuild -ba SPECS/ilc-marlin-kinfit.spec
sudo yum -y localinstall RPMS/x86_64/ilc-marlin-util* \
                         RPMS/x86_64/ilc-ddkaltest* \
                         RPMS/x86_64/ilc-kitrack* \
                         RPMS/x86_64/ilc-marlin-kinfit*

rpmbuild -ba SPECS/ilc-ced-viewer.spec
rpmbuild -ba SPECS/ilc-kaldet.spec
rpmbuild -ba SPECS/ilc-garlic.spec
rpmbuild -ba SPECS/lcfi-vertex.spec
rpmbuild -ba SPECS/ilc-marlin-kinfit-processors.spec
rpmbuild -ba SPECS/ilc-overlay.spec
rpmbuild -ba SPECS/pandora-analysis.spec
rpmbuild -ba SPECS/lcfi-plus-headers.spec
sudo yum -y localinstall RPMS/x86_64/lcfi-vertex* \
                         RPMS/x86_64/lcfi-plus-headers* \
                         RPMS/x86_64/ilc-kaldet-*

rpmbuild -ba SPECS/ilc-marlin-trk.spec
rpmbuild -ba SPECS/lcfi-plus.spec
sudo yum -y localinstall RPMS/x86_64/ilc-marlin-trk*

rpmbuild -ba SPECS/ilc-conformal-tracking.spec
rpmbuild -ba SPECS/ilc-ddmarlin-pandora.spec
rpmbuild -ba SPECS/ilc-kitrack-marlin.spec
rpmbuild -ba SPECS/ilc-clic-performance.spec
rpmbuild -ba SPECS/ilc-marlin-reco.spec
sudo yum -y localinstall RPMS/x86_64/ilc-kitrack-marlin*

QA_SKIP_BUILD_ROOT=1 rpmbuild -ba SPECS/ilc-acts-tracking.spec
rpmbuild -ba SPECS/ilc-forward-tracking.spec
rpmbuild -ba SPECS/ilc-marlin-trk-processors.spec
rpmbuild -ba SPECS/muonc-tracker-digitizer.spec
rpmbuild -ba SPECS/muonc-base-installation.spec

# See https://access.redhat.com/articles/3359321

