#!/bin/bash

set -e

sudo yum -y install epel-release yum-utils wget git

sudo yum-config-manager --set-enabled PowerTools
sudo yum-config-manager --set-enabled AppStream

sudo wget -O /etc/yum.repos.d/EGI-trustanchors.repo http://repository.egi.eu/sw/production/cas/1/current/repo-files/EGI-trustanchors.repo
sudo yum -y install ca-policy-egi-core
sudo ln -s /etc/grid-security/certificates/USERTrustRSACertificationAuthority.pem /etc/pki/ca-trust/source/anchors/
sudo ln -s /etc/grid-security/certificates/GEANTeScienceSSLCA4.pem /etc/pki/ca-trust/source/anchors/
sudo update-ca-trust extract

sudo wget -O /etc/yum.repos.d/geant4.repo http://artifacts.pd.infn.it/packages/MuonColliderSoft/repos/CentOS8/geant4.repo

sudo yum -y install boost169-devel chrpath clhep-devel cmake doxygen \
                    eigen3-devel freeglut-devel geant4-devel \
                    gsl-devel make mysql-devel python36 \
                    python36-rpm-macros python3-root root root-gdml \
                    root-genvector root-geom root-graf3d-eve \
                    root-tmva root-minuit2 root-unuran root-smatrix \
                    zlib-devel rpm-build

sudo geant4-dataset-download

sudo sed -i 's|include_next|include|g' /usr/include/c++/8/cstdlib
sudo sed -i 's|include_next|include|g' /usr/include/c++/8/bits/std_abs.h
sudo sed -i 's|include_next|include|g' /usr/include/c++/8/cmath

cat << EOF > $HOME/.rpmmacros
%mc_source_url https://cld-smact-02.pd.infn.it/artifacts/repository/mc-sources
EOF

sudo alternatives --set python /usr/bin/python3

git clone https://github.com/MuonColliderSoft/MuonCollider-rpms.git
ln -s $HOME/MuonCollider-rpms/CentOS8/ $HOME/rpmbuild
cd rpmbuild

rpmbuild -ba SPECS/ilc-utils.spec
sudo yum -y localinstall RPMS/x86_64/ilc-utils*

rpmbuild -ba SPECS/ilc-ced.spec
rpmbuild -ba SPECS/ilc-gear.spec
rpmbuild -ba SPECS/ilc-fastjet.spec
rpmbuild -ba SPECS/ilc-cond-db-mysql.spec
rpmbuild -ba SPECS/ilc-lcio.spec
rpmbuild -ba SPECS/gbl.spec
rpmbuild -ba SPECS/root-aida.spec
rpmbuild -ba SPECS/ilc-kaltest.spec
QA_SKIP_BUILD_ROOT=1 rpmbuild -ba SPECS/pandora-pfa.spec
rpmbuild -ba SPECS/ilc-physsim.spec
sudo yum -y localinstall RPMS/x86_64/ilc-ced* \
                         RPMS/x86_64/ilc-gear* \
                         RPMS/x86_64/ilc-fastjet* \
                         RPMS/x86_64/ilc-cond-db-mysql* \
                         RPMS/x86_64/ilc-lcio* \
                         RPMS/x86_64/gbl* \
                         RPMS/x86_64/root-aida* \
                         RPMS/x86_64/ilc-kaltest* \
                         RPMS/x86_64/pandora-pfa*

rpmbuild -ba SPECS/aida-dd4hep.spec
rpmbuild -ba SPECS/ilc-lccd.spec
rpmbuild -ba SPECS/ilc-fastjet-contrib.spec
sudo yum -y localinstall RPMS/x86_64/aida-dd4hep* \
                         RPMS/x86_64/ilc-lccd* \
                         RPMS/x86_64/ilc-fastjet-contrib*

rpmbuild -ba SPECS/aida-tracking-toolkit.spec
rpmbuild -ba SPECS/ilc-marlin.spec
rpmbuild -ba SPECS/ilc-lcgeo.spec
sudo yum -y localinstall RPMS/x86_64/aida-tracking-toolkit* \
                         RPMS/x86_64/ilc-marlin*

rpmbuild -ba SPECS/ilc-marlin-util.spec
rpmbuild -ba SPECS/ilc-ddkaltest.spec
rpmbuild -ba SPECS/ilc-fcal-clusterer.spec
rpmbuild -ba SPECS/ilc-kitrack.spec
rpmbuild -ba SPECS/ilc-lctuple.spec
rpmbuild -ba SPECS/ilc-marlin-dd4hep.spec
rpmbuild -ba SPECS/ilc-marlin-fastjet.spec
rpmbuild -ba SPECS/ilc-marlin-kinfit.spec
sudo yum -y localinstall RPMS/x86_64/ilc-marlin-util* \
                         RPMS/x86_64/ilc-ddkaltest* \
                         RPMS/x86_64/ilc-kitrack* \
                         RPMS/x86_64/ilc-marlin-kinfit*

rpmbuild -ba SPECS/ilc-ced-viewer.spec
rpmbuild -ba SPECS/ilc-kaldet.spec
rpmbuild -ba SPECS/ilc-garlic.spec
rpmbuild -ba SPECS/ilc-lcfi-vertex.spec
rpmbuild -ba SPECS/ilc-marlin-kinfit-processors.spec
rpmbuild -ba SPECS/ilc-marlin-lich.spec
rpmbuild -ba SPECS/ilc-overlay.spec
rpmbuild -ba SPECS/pandora-analysis.spec
sudo yum -y localinstall RPMS/x86_64/ilc-ced-viewer* \
                         RPMS/x86_64/ilc-kaldet* \
                         RPMS/x86_64/ilc-lcfi-vertex*

rpmbuild -ba SPECS/ilc-marlin-trk.spec
rpmbuild -ba SPECS/ilc-lcfi-plus.spec
sudo yum -y localinstall RPMS/x86_64/ilc-marlin-trk*

rpmbuild -ba SPECS/ilc-clupatra.spec
rpmbuild -ba SPECS/ilc-conformal-tracking.spec
rpmbuild -ba SPECS/ilc-ddmarlin-pandora.spec
rpmbuild -ba SPECS/ilc-kitrack-marlin.spec
rpmbuild -ba SPECS/ilc-ild-preformance.spec
rpmbuild -ba SPECS/ilc-marlin-reco.spec
sudo yum -y localinstall RPMS/x86_64/ilc-ddmarlin-pandora* \
                         RPMS/x86_64/ilc-kitrack-marlin*

rpmbuild -ba SPECS/ilc-forward-tracking.spec
rpmbuild -ba SPECS/ilc-marlin-trk-processors.spec








