#!/bin/bash


#
# Apply patches as reported in the recipe:
#
# #undef _GLIBCXX_ASSERTIONS in
# /usr/include/c++/11/x86_64-redhat-linux/bits/c++config.h
# /usr/include/c++/11/x86_64-redhat-linux/32/bits/c++config.h 
#

set -e

rpmbuild -ba SPECS/ilc-utils.spec
rpmbuild -ba SPECS/podio.spec
rpmbuild -ba SPECS/ilc-kaltest-headers.spec
rpmbuild -ba SPECS/cpp-gsl-devel.spec
rpmbuild -ba SPECS/ilc-sio.spec
sudo yum -y localinstall RPMS/x86_64/ilc-utils* \
                         RPMS/x86_64/podio* RPMS/noarch/*podio* \
                         RPMS/x86_64/ilc-kaltest-headers* \
                         RPMS/x86_64/cpp-gsl-devel-* \
                         RPMS/x86_64/ilc-sio-*

rpmbuild -ba SPECS/ilc-ced.spec
rpmbuild -ba SPECS/ilc-gear.spec
rpmbuild -ba SPECS/fastjet.spec
rpmbuild -ba SPECS/ilc-lcio-headers.spec
rpmbuild -ba SPECS/gbl-toolkit.spec
rpmbuild -ba SPECS/ilc-root-aida.spec
rpmbuild -ba SPECS/ilc-kaltest.spec
rpmbuild -ba SPECS/pandora-pfa.spec
sudo yum -y localinstall RPMS/x86_64/ilc-ced* \
                         RPMS/x86_64/ilc-gear* \
                         RPMS/x86_64/fastjet* \
                         RPMS/x86_64/ilc-lcio-headers* \
                         RPMS/x86_64/gbl-toolkit* \
                         RPMS/x86_64/ilc-root-aida* \
                         RPMS/x86_64/ilc-kaltest-2* \
                         RPMS/x86_64/ilc-kaltest-dev* \
                         RPMS/x86_64/pandora-pfa*

rpmbuild -ba SPECS/ilc-lcio.spec
rpmbuild -ba SPECS/edm4hep.spec
sudo yum -y localinstall RPMS/x86_64/ilc-lcio-2* \
                         RPMS/x86_64/ilc-lcio-dev* \
                         RPMS/x86_64/edm4hep-*

rpmbuild -ba SPECS/aida-dd4hep.spec
rpmbuild -ba SPECS/fastjet-contrib.spec
sudo yum -y localinstall RPMS/x86_64/aida-dd4hep* \
                         RPMS/x86_64/fastjet-contrib*

rpmbuild -ba SPECS/acts-toolkit.spec
rpmbuild -ba SPECS/aida-tracking-toolkit.spec
rpmbuild -ba SPECS/ilc-marlin.spec
rpmbuild -ba SPECS/ilc-lcgeo.spec
sudo yum -y localinstall RPMS/x86_64/aida-tracking-toolkit* \
                         RPMS/x86_64/acts-toolkit* \
                         RPMS/x86_64/ilc-marlin*

rpmbuild -ba SPECS/ilc-marlin-util.spec
rpmbuild -ba SPECS/ilc-ddkaltest.spec
rpmbuild -ba SPECS/ilc-kitrack.spec
rpmbuild -ba SPECS/ilc-lctuple.spec
rpmbuild -ba SPECS/ilc-marlin-dd4hep.spec
rpmbuild -ba SPECS/ilc-marlin-fastjet.spec
rpmbuild -ba SPECS/ilc-marlin-kinfit.spec
rpmbuild -ba SPECS/ilc-kaldet-headers.spec
sudo yum -y localinstall RPMS/x86_64/ilc-marlin-util* \
                         RPMS/x86_64/ilc-ddkaltest* \
                         RPMS/x86_64/ilc-kitrack* \
                         RPMS/x86_64/ilc-marlin-kinfit* \
                         RPMS/x86_64/ilc-kaldet-headers*

rpmbuild -ba SPECS/ilc-ced-viewer.spec
rpmbuild -ba SPECS/ilc-kaldet.spec
rpmbuild -ba SPECS/ilc-garlic.spec
rpmbuild -ba SPECS/lcfi-vertex.spec
rpmbuild -ba SPECS/ilc-marlin-kinfit-processors.spec
rpmbuild -ba SPECS/ilc-overlay.spec
rpmbuild -ba SPECS/pandora-analysis.spec
rpmbuild -ba SPECS/lcfi-plus-headers.spec
sudo yum -y localinstall RPMS/x86_64/lcfi-vertex* \
                         RPMS/x86_64/lcfi-plus-headers* \
                         RPMS/x86_64/ilc-kaldet-1* \
                         RPMS/x86_64/ilc-kaldet-devel*

rpmbuild -ba SPECS/ilc-marlin-trk.spec
rpmbuild -ba SPECS/lcfi-plus.spec
sudo yum -y localinstall RPMS/x86_64/ilc-marlin-trk*

rpmbuild -ba SPECS/ilc-conformal-tracking.spec
rpmbuild -ba SPECS/ilc-ddmarlin-pandora.spec
rpmbuild -ba SPECS/ilc-kitrack-marlin.spec
rpmbuild -ba SPECS/ilc-clic-performance.spec
rpmbuild -ba SPECS/ilc-marlin-reco.spec
sudo yum -y localinstall RPMS/x86_64/ilc-kitrack-marlin*

rpmbuild -ba SPECS/ilc-acts-tracking.spec
rpmbuild -ba SPECS/ilc-forward-tracking.spec
rpmbuild -ba SPECS/ilc-marlin-trk-processors.spec
rpmbuild -ba SPECS/muonc-tracker-digitizer.spec
rpmbuild -ba SPECS/muonc-base-installation.spec

# See https://access.redhat.com/articles/3359321

sudo yum -y localinstall RPMS/x86_64/ilc-acts-tracking-* \
                         RPMS/x86_64/ilc-ced-viewer-* \
                         RPMS/x86_64/ilc-clic-performance-* \
                         RPMS/x86_64/ilc-conformal-tracking-* \
                         RPMS/x86_64/ilc-ddmarlin-pandora-* \
                         RPMS/x86_64/ilc-forward-tracking-* \
                         RPMS/x86_64/ilc-lctuple-* \
                         RPMS/x86_64/ilc-marlin-dd4hep-* \
                         RPMS/x86_64/ilc-marlin-kinfit-processors-* \
                         RPMS/x86_64/ilc-marlin-reco-* \
                         RPMS/x86_64/ilc-marlin-trk-processors-* \
                         RPMS/x86_64/ilc-overlay-* \
                         RPMS/x86_64/lcfi-plus-* \
                         RPMS/x86_64/ilc-lcgeo-* \
                         RPMS/x86_64/ilc-marlin-fastjet-* \
                         RPMS/x86_64/ilc-lcio-tools-* \
                         RPMS/x86_64/muonc-tracker-digitizer-* \
                         RPMS/noarch/muonc-detector-geometry-* \
                         RPMS/noarch/python3-* \
                         RPMS/noarch/muonc-base-installation-*

rpmbuild -ba SPECS/gaudi.spec
sudo yum -y localinstall RPMS/x86_64/*gaudi*

rpmbuild -ba SPECS/key4hep-fw-core.spec
sudo yum -y localinstall RPMS/x86_64/key4hep-fw-core-* \
                         RPMS/noarch/*k4fwcore*

rpmbuild -ba SPECS/key4hep-edm4hep2lcio.spec
sudo yum -y localinstall RPMS/x86_64/key4hep-edm4hep2lcio-*

rpmbuild -ba SPECS/key4hep-marlin-wrapper.spec
sudo yum -y localinstall RPMS/x86_64/key4hep-marlin-wrapper*

